name: webserver

on:
  push:
    branches:
      - master

jobs:
  gradle-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v2

      - name: 'set up JDK 17'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: 'grant execute permission for gradlew'
        run: chmod +x gradlew

      - name: 'tests'
        run: ./gradlew test

      - name: 'execute gradle build'
        run: ./gradlew build



