name: webserver

on:
  push:
    branches:
      - master

jobs:
  gradle-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v3

      - name: 'set up JDK 17'
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle

      - name: 'setup gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'grant execute permission for gradlew'
        run: chmod +x gradlew

      - name: 'tests'
        run: ./gradlew test

      - name: 'execute gradle build'
        run: ./gradlew build

      - name: 'login to heroku'
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password: $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password: $HEROKU_API_KEY
          EOF
        env:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: 'add heroku remote'
        run: |
          heroku git:remote -a quizle-api

      - name: 'push to heroku'
        run: |
          git push heroku master
