name: webserver

on:
  push:
    branches:
      - master

jobs:
  gradle-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v3

      - name: 'set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: 'setup gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'execute gradle build'
        run: ./gradlew build

      - name: 'deploy on netlify'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}